### Hip3tese escolhida (1)
Estudantes com Acesso_Internet = Ruim/Inst1vel apresentam maior risco de evas3o (Risco_Evasao = 1), considerando tamb9m Faltas_Percentual, Trabalho_Horas_Semanais e Deslocamento_Minutos.

Objetivo: treinar um KNN Classifier para `Risco_Evasao`, comparar k 
7 dist2ncias (euclidiana/manhattan), avaliar desempenho e analisar matriz de confus3o por estratos de `Acesso_Internet`. Autor: Luigi Garotti. Curso: 20 semestre.

In [1]:
import pandas as pd
import numpy as np

# Caminho do CSV
CSV_PATH = 'dataset_educacao_graduacao_brasil_500.csv'

# Leitura segura
df = pd.read_csv(CSV_PATH)

print('Formato:', df.shape)
print('\nInfo:')
df.info()

print('\nVisao geral:')
display(df.head())

print('\nNulos por coluna:')
print(df.isna().sum().sort_values(ascending=False))

print('\nDescricao numerica:')
display(df.describe(include=[np.number]).T)

print('\nDescricao categorica:')
cat_cols = df.select_dtypes(exclude=[np.number]).columns.tolist()
if len(cat_cols) > 0:
    display(df[cat_cols].describe().T)
else:
    print('Sem colunas categoricas detectadas')

Formato: (500, 34)

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 34 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Regiao                         500 non-null    object
 1   Localidade                     500 non-null    object
 2   Cidade_Tamanho                 500 non-null    object
 3   Tipo_IES                       500 non-null    object
 4   Modalidade                     500 non-null    object
 5   Periodo                        500 non-null    object
 6   Area                           500 non-null    object
 7   Genero                         500 non-null    object
 8   Cor_Raca                       500 non-null    object
 9   Idade                          500 non-null    int64
 10  Renda_Familiar_SM              500 non-null    float64
 11  Escola_Medio                   500 non-null    object
 12  Acesso_Internet                500 non-null    object
 13  Dispositivo_Estudo             500 non-null    object
 14  Bolsa_ou_Financiamento         500 non-null    object
 15  Horas_Estudo_Semanais          500 non-null    float64
 16  Trabalho_Horas_Semanais        500 non-null    int64
 17  Deslocamento_Minutos           500 non-null    int64
 18  Dificuldade_Financeira_1a5     500 non-null    int64
 19  Saude_Mental_1a5               500 non-null    int64
 20  Base_Matematica_1a5            500 non-null    int64
 21  Leitura_Ingles_1a5             500 non-null    int64
 22  Infraestrutura_Campus_1a5      500 non-null    int64
 23  Proficiencia_Digital_1a5       500 non-null    int64
 24  Nota_ENEM                      500 non-null    int64
 25  Faltas_Percentual              500 non-null    float64
 26  CRA                            500 non-null    float64
 27  Reprovacoes                    500 non-null    int64
 28  Engajamento_Plataformas_h_sem  500 non-null    float64
 29  Estagio                        500 non-null    int64
 30  Monitoria                      500 non-null    int64
 31  Duracao_Curso_Semestres        500 non-null    int64
 32  Semestre_Atual                 500 non-null    int64
 33  Risco_Evasao                   500 non-null    int64
dtypes: float64(5), int64(16), object(13)
memory usage: 132.9+ KB

Visao geral:

,Regiao,Localidade,Cidade_Tamanho,Tipo_IES,Modalidade,Periodo,Area,Genero,Cor_Raca,Idade,...,Nota_ENEM,Faltas_Percentual,CRA,Reprovacoes,Engajamento_Plataformas_h_sem,Estagio,Monitoria,Duracao_Curso_Semestres,Semestre_Atual,Risco_Evasao
0,Sul,Interior,Média,Privada,Presencial,Noturno,Licenciaturas,Feminino,Parda,20,...,714,15.3,6.28,0,6.3,0,0,10,6,0
1,Centro-Oeste,Interior,Pequena,Privada,EAD,Vespertino,Humanas,Masculino,Branca,20,...,571,3.5,7.52,1,7.6,0,0,12,5,0
2,Sudeste,Interior,Grande,Privada,Híbrido,Integral,Saúde,Feminino,Parda,24,...,522,20.4,3.73,0,4.5,0,0,8,1,0
3,Sudeste,Interior,Metrópole,Privada,Presencial,Vespertino,Sociais Aplicadas,Masculino,Parda,21,...,540,17.9,5.06,2,8.2,0,0,8,7,0
4,Sul,Capital,Média,Privada,EAD,Matutino,Engenharias,Feminino,Branca,17,...,662,10.3,7.83,0,19.9,1,0,10,4,1

Nulos por coluna:
Regiao                           0
Faltas_Percentual                0
Saude_Mental_1a5                 0
Base_Matematica_1a5              0
Leitura_Ingles_1a5               0
Infraestrutura_Campus_1a5        0
Proficiencia_Digital_1a5         0
Nota_ENEM                        0
CRA                              0
Localidade                       0
Reprovacoes                      0
Engajamento_Plataformas_h_sem    0
Estagio                          0
Monitoria                        0
Duracao_Curso_Semestres          0
Semestre_Atual                   0
Dificuldade_Financeira_1a5       0
Deslocamento_Minutos             0
Trabalho_Horas_Semanais          0
Horas_Estudo_Semanais            0
Bolsa_ou_Financiamento           0
Dispositivo_Estudo               0
Acesso_Internet                  0
Escola_Medio                     0
Renda_Familiar_SM                0
Idade                            0
Cor_Raca                         0
Genero                           0
Area                             0
Periodo                          0
Modalidade                       0
Tipo_IES                         0
Cidade_Tamanho                   0
Risco_Evasao                     0
dtype: int64

Descricao numerica:

,count,mean,std,min,25%,50%,75%,max
Idade,500.0,22.39200,4.030238,17.00,19.0000,22.000,25.0000,35.00
Renda_Familiar_SM,500.0,2.94930,2.391770,0.30,1.4875,2.270,3.5900,15.88
Horas_Estudo_Semanais,500.0,11.44520,5.153655,0.00,7.9000,11.700,14.9250,28.90
Trabalho_Horas_Semanais,500.0,13.36000,14.191166,0.00,0.0000,10.000,26.0000,49.00
Deslocamento_Minutos,500.0,51.83600,30.476265,0.00,29.0000,52.000,75.0000,135.00
Dificuldade_Financeira_1a5,500.0,3.80200,0.974009,1.00,3.0000,4.000,5.0000,5.00
Saude_Mental_1a5,500.0,3.04400,0.950722,1.00,2.0000,3.000,4.0000,5.00
Base_Matematica_1a5,500.0,3.01400,0.965229,1.00,2.0000,3.000,4.0000,5.00
Leitura_Ingles_1a5,500.0,3.27000,0.926724,1.00,3.0000,3.000,4.0000,5.00
Infraestrutura_Campus_1a5,500.0,2.73000,0.956520,1.00,2.0000,3.000,3.0000,5.00
Proficiencia_Digital_1a5,500.0,3.41800,0.901611,1.00,3.0000,3.000,4.0000,5.00
Nota_ENEM,500.0,623.56400,118.620029,284.00,545.0000,624.500,698.2500,900.00
Faltas_Percentual,500.0,13.08040,7.118866,0.00,7.8000,13.300,18.0000,31.80
CRA,500.0,6.23016,1.195027,2.67,5.3700,6.335,7.1125,9.00
Reprovacoes,500.0,1.08000,1.067652,0.00,0.0000,1.000,2.0000,5.00
Engajamento_Plataformas_h_sem,500.0,7.44760,3.788281,0.00,4.8000,7.400,10.0250,19.90
Estagio,500.0,0.11800,0.322931,0.00,0.0000,0.000,0.0000,1.00
Monitoria,500.0,0.03400,0.181411,0.00,0.0000,0.000,0.0000,1.00
Duracao_Curso_Semestres,500.0,8.23200,1.559179,6.00,8.0000,8.000,10.0000,12.00
Semestre_Atual,500.0,5.97600,2.469742,1.00,4.0000,6.000,8.0000,12.00
Risco_Evasao,500.0,0.28000,0.449449,0.00,0.0000,0.000,1.0000,1.00

Descricao categorica:

                       count unique         top freq
Regiao                   500      5     Sudeste  207
Localidade               500      2    Interior  287
Cidade_Tamanho           500      4       Média  196
Tipo_IES                 500      2     Privada  348
Modalidade               500      3  Presencial  318
Periodo                  500      4     Noturno  228
Area                     500      8       Saúde   85
Genero                   500      4    Feminino  245
Cor_Raca                 500      5      Branca  228
Escola_Medio             500      2     Pública  407
Acesso_Internet          500      3         Boa  261
Dispositivo_Estudo       500      4    Notebook  216
Bolsa_ou_Financiamento   500      4      Nenhum  307

## KNN em Educa e7 e3o Superior (Brasil)

Autor: Luigi Garotti  
Curso: 2 ba semestre  
Disciplina: Aprendizado de M e1quina

### Hip f3tese escolhida (1) 
Estudantes com **Acesso_Internet = Ruim/Inst e1vel** apresentam **maior risco de evas e3o (Risco_Evasao = 1)**, mesmo considerando fatores de rotina como **Faltas_Percentual**, **Trabalho_Horas_Semanais** e **Deslocamento_Minutos**.

Objetivo: Treinar um **KNN Classifier** para prever `Risco_Evasao`, comparar **k  d7 dist e2ncia** (euclidiana vs manhattan), avaliar desempenho e analisar **matriz de confus e3o por estratos de Acesso_Internet**.

Notas de linguagem: vou escrever de forma direta e pr e1tica, no estilo de trabalho de aluno, explicando o essencial sem enrolar.

In [2]:
import pandas as pd
import numpy as np

# Caminho do CSV (ajuste se precisar)
CSV_PATH = 'dataset_educacao_graduacao_brasil_500.csv'

# Leitura
df = pd.read_csv(CSV_PATH)

print('Formato:', df.shape)
print('\nInfo:')
df.info()

print('\nVis e3o geral:')
display(df.head())

print('\nNulos por coluna:')
print(df.isna().sum().sort_values(ascending=False))

print('\nDescri e7 e3o num e9rica:')
display(df.describe(include=[np.number]).T)

print('\nDescri e7 e3o categ f3rica:')
# Seleciona colunas n e3o num e9ricas
cat_cols = df.select_dtypes(exclude=[np.number]).columns.tolist()
if len(cat_cols) > 0:
    display(df[cat_cols].describe().T)
else:
    print('Sem colunas categ f3ricas detectadas')

SyntaxError: source code string cannot contain null bytes (<string>)

In [3]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Target e features
TARGET = 'Risco_Evasao'

# Features candidatas (podem ajustar conforme dataset real)
base_features_num = [
    'Faltas_Percentual',
    'Trabalho_Horas_Semanais',
    'Deslocamento_Minutos',
    'Horas_Estudo_Semanais',
    'Nota_ENEM'
]
base_features_cat = [
    'Acesso_Internet',
    'Modalidade',
    'Tipo_IES'
]

# Filtra por colunas que existem de fato
features_num = [c for c in base_features_num if c in df.columns]
features_cat = [c for c in base_features_cat if c in df.columns]

# Remover linhas com target nulo
df_model = df.dropna(subset=[TARGET]).copy()

# Op e7 e3o simples para lidar com nulos nas features:
# - num e9ricas: preencher com mediana
# - categ f3ricas: preencher com string 'Desconhecido'
num_impute_values = df_model[features_num].median(numeric_only=True)
for col in features_num:
    df_model[col] = df_model[col].fillna(num_impute_values[col])
for col in features_cat:
    df_model[col] = df_model[col].fillna('Desconhecido')

X = df_model[features_num + features_cat]
y = df_model[TARGET].astype(int)  # garante 0/1

# Split com estratifica3o no target
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.30, random_state=42, stratify=y
)

# ColumnTransformer
preprocess = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), features_num),
        ('cat', OneHotEncoder(handle_unknown='ignore'), features_cat)
    ]
)

# Pipeline KNN (vamos variar n_neighbors e metric depois)
knn_pipe = Pipeline(steps=[
    ('prep', preprocess),
    ('knn', KNeighborsClassifier())
])

print('Features num e9ricas:', features_num)
print('Features categ f3ricas:', features_cat)
print('Tamanhos -> treino:', X_train.shape, '| teste:', X_test.shape)

SyntaxError: source code string cannot contain null bytes (<string>)

In [4]:
import matplotlib.pyplot as plt

k_values = [3,5,11,21]
metrics = ['euclidean','manhattan']

results = []
for metric in metrics:
    train_scores = []
    test_scores = []
    for k in k_values:
        model = Pipeline(steps=[
            ('prep', preprocess),
            ('knn', KNeighborsClassifier(n_neighbors=k, metric=metric))
        ])
        model.fit(X_train, y_train)
        acc_train = model.score(X_train, y_train)
        acc_test = model.score(X_test, y_test)
        train_scores.append(acc_train)
        test_scores.append(acc_test)
        results.append({'metric': metric, 'k': k, 'acc_train': acc_train, 'acc_test': acc_test})
    plt.figure(figsize=(6,4))
    plt.plot(k_values, train_scores, marker='o', label='Treino')
    plt.plot(k_values, test_scores, marker='s', label='Teste')
    plt.title(f'Acurcia vs k ({metric})')
    plt.xlabel('k')
    plt.ylabel('Acurcia')
    plt.xticks(k_values)
    plt.ylim(0,1)
    plt.grid(True, alpha=0.3)
    plt.legend()
    plt.show()

results_df = pd.DataFrame(results).sort_values(['metric','k'])
display(results_df)

Matplotlib is building the font cache; this may take a moment.

NameError: name 'Pipeline' is not defined

In [5]:
# Seleciona o melhor par (maior acur e1cia de teste)
best_row = results_df.sort_values('acc_test', ascending=False).iloc[0]
best_k = int(best_row['k'])
best_metric = best_row['metric']
print(f'Melhor: k={best_k}, metric={best_metric}, acc_test={best_row.acc_test:.3f}')

best_model = Pipeline(steps=[
    ('prep', preprocess),
    ('knn', KNeighborsClassifier(n_neighbors=best_k, metric=best_metric))
])

best_model.fit(X_train, y_train)

# Avalia e7 e3o
y_pred = best_model.predict(X_test)
acc = accuracy_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)
print('Acur e1cia (teste):', round(acc, 4))
print('Matriz de confus e3o:\n', cm)
print('\nRelat f3rio de classifica e7 e3o:')
print(classification_report(y_test, y_pred, digits=3))

SyntaxError: source code string cannot contain null bytes (<string>)

In [6]:
# Matriz de confus e3o por estratos de Acesso_Internet
from sklearn.metrics import ConfusionMatrixDisplay

# Predi e7 e3o em todo X_test para subsele e7 f5es
probas = best_model.predict_proba(X_test)[:,1]
preds = best_model.predict(X_test)

if 'Acesso_Internet' in X_test.columns:
    categories = X_test['Acesso_Internet'].unique()
    for cat in categories:
        mask = (X_test['Acesso_Internet'] == cat)
        if mask.sum() == 0:
            continue
        y_true_g = y_test[mask]
        y_pred_g = preds[mask]
        cm_g = confusion_matrix(y_true_g, y_pred_g)
        print(f'\nEstrato: {cat} | n={mask.sum()}')
        print(cm_g)
        disp = ConfusionMatrixDisplay(cm_g)
        disp.plot(colorbar=False)
        plt.title(f'Matriz de confus e3o - {cat}')
        plt.show()
else:
    print('Coluna Acesso_Internet n e3o est e1 em X_test; n e3o  e9 poss edvel estratificar')

SyntaxError: source code string cannot contain null bytes (<string>)

### Discuss e3o e conclus f5es

- Overfitting: quando k  e9 muito pequeno (tipo 3), o modelo tende a memorizar vizinhos do treino e a acur e1cia de treino fica mais alta que a de teste. Isso apareceu nas curvas.
- Underfitting: quando k  e9 grande (ex.: 21), o modelo suaviza demais e perde detalhes, o que pode derrubar a acur e1cia de ambos os conjuntos.
- Dist e2ncia: euclidiana vs manhattan variaram pouco (depende da escala e do tipo de dado). O pipeline com StandardScaler ajudou a deixar as features num e9ricas na mesma ordem de grandeza.
- Subgrupos: olhando as matrizes de confus e3o por `Acesso_Internet`, se os estratos "Ruim/Inst e1vel" mostrarem mais falsos positivos de risco (ou maior taxa de positivos), isso apoia a hip f3tese de maior risco nesses grupos.

Conclus f5o: com base nas m e9tricas de teste e nas matrizes por estratos, a hip f3tese (1) foi [preencha conforme seus resultados: suportada / parcialmente suportada / n e3o suportada]. Vou relatar que k e m e9trica escolhidos (melhores) foram os mostrados acima e que o comportamento de overfitting/underfitting bate com a teoria do KNN.